### PR TITLE
Add message content dynamically

### PR DESCRIPTION
**Pull request by aljones15**
@liamdennehy I don't have a lot of time for this today, but let me know if this works for you.
Sorry about the mistake.

### CODE REVIEW

**Comment by aljones15** [comment]
@liamdennehy hey sorry about the issues here. I removed the Date Header from all the http Messages.

```
grep -inr date ./test/latest/input
```
is now empty. The node implementation is happy with these changes. I will look into the `\n` you discovered in the messages with a signature. Momentarily. Don't be afraid to clean stuff up. I have a lot on my plate these days and so far your changes have helped immensely.

**Comment by aljones15** [comment]
@liamdennehy hey is this PR ok now or not?

**Comment by liamdennehy** [comment]
> @liamdennehy hey is this PR ok now or not?

Will do some testing today, thx.

**Comment by liamdennehy** [comment]
> @liamdennehy hey is this PR ok now or not?

Looks good. There are some small issues, but they're either cosmetic or from confusion in the spec, so this can go on and we'll address them later.

**Pull request merged**
